name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:    
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1

    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
          
    - name: Install dependencies
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run rubocop
      env:
        RAILS_ENV: development
      run: bundle exec rubocop
